version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "library_db"
    ports:
      - "3306:3306"
    volumes:
      - ./library_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: library_app
    environment:
      DB_HOST: mysql
    ports:
      - "80:8080"
    depends_on:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: library_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped
